Repository SavandBros/gonevis-dash, pull requests merged in 2018-07, with the labels that each got.

#914 Advanced view for files
  CHANGELOG.md
  src/app/dolphin/dolphin_modal/dolphin_modal_view.html
  src/app/dolphin/dolphin_view.html
  src/public/languages/en.json
  src/style/css/main.css
Labels: enhancement, needs review

#917 Release 2018.7.2
  .circleci/config.yml
  .jshintrc
  CHANGELOG.md
  README.md
  circle.yml
  package-lock.json
  package.json
  src/app/account/account_service.js
  src/app/account/auth/auth_service.js
  src/app/account/email_confirmation/email_confirmation_controller.js
  src/app/app_config.js
  src/app/app_routes.js
  src/app/app_run.js
  src/app/basement/filters/timesince_filter.js
  src/app/basement/filters/timeuntil_filter.js
  src/app/basement/medium_editor/medium_editor.js
  src/app/basement/pagination/pagination_loadmore.html
  src/app/basement/pagination/pagination_service.js
  src/app/basement/tour/tour_service.js
  src/app/dolphin/dolphin_controller.js
  src/app/dolphin/dolphin_modal/dolphin_modal_view.html
  src/app/dolphin/dolphin_selection.html
  src/app/dolphin/dolphin_view.html
  src/app/entry/entry_edit/entry_edit_controller.js
  src/app/header/header_view.html
  src/app/site/site_followers/site_followers_view.html
  src/app/tag/tag_controller.js
  src/app/tag/tag_modal/tag_modal_controller.js
  src/app/team/team_modal/team_modal_controller.js
  src/public/index.html
  src/public/languages/en.json
  src/public/languages/fa.json
  src/style/css/main.css
  src/style/css/shorties.css
Labels: needs review

#920 Update all packages to latest
  package-lock.json
  package.json
Labels: needs review

#921 Remember last site
  CHANGELOG.md
  src/app/app.js
  src/app/app_routes.js
  src/app/app_run.js
  src/app/header/header_controller.js
  src/app/header/header_view.html
Labels: needs review

#904 Add Auto-Save mode method
  CHANGELOG.md
  src/app/entry/entry_edit/entry_edit_controller.js
  src/app/entry/entry_edit/entry_edit_view.html
  src/app/entry/status.js
  src/public/languages/en.json
Labels: help wanted, needs review

#928 Fix loadmore button for file selection
  src/app/basement/pagination/pagination_loadmore.html
Labels: bug, needs review

#929 Close comment modal after reply
  CHANGELOG.md
  src/app/comment/comment_modal/comment_modal_view.html
  src/app/comment/comment_service.js
Labels: bug, needs review

#927 Set commenting enabled by default
  CHANGELOG.md
  src/app/entry/entry_edit/entry_edit_controller.js
Labels: bug, needs review

#930 Update changelog
  CHANGELOG.md
Labels: enhancement, needs review

#931 Filter image selection for images only via backend
  CHANGELOG.md
  src/app/dolphin/dolphin_controller.js
  src/app/dolphin/dolphin_service.js
  src/style/css/main.css
Labels: enhancement, needs review

#923 Use Quill editor instead of MediumEditor
  CHANGELOG.md
  package-lock.json
  package.json
  src/app/app.js
  src/app/app_config.js
  src/app/app_routes.js
  src/app/app_run.js
  src/app/basement/medium_editor/medium_editor.js
  src/app/entry/entry_edit/editor.css
  src/app/entry/entry_edit/entry_edit_controller.js
  src/app/entry/entry_edit/entry_edit_view.html
  src/app/vendor.js
  src/style/css/ice.css
  src/style/css/main.css
Labels: enhancement, needs review

#933 Add color picker for navigation
  CHANGELOG.md
  src/app/navigation/navigation_view.html
  src/style/css/main.css
  src/style/css/shorties.css
Labels: enhancement, needs review

#934 Install RSync before running the deploy script
  .circleci/config.yml
  CHANGELOG.md
  scripts/deploy.sh
Labels: enhancement, needs review

#935 Release 2018.7.15
  .circleci/config.yml
  CHANGELOG.md
  scripts/deploy.sh
  src/app/navigation/navigation_view.html
  src/style/css/main.css
  src/style/css/shorties.css
Labels: needs review

#938 937 improve editor
  CHANGELOG.md
  src/app/entry/entry_edit/editor.css
  src/app/entry/entry_edit/entry_edit_controller.js
  src/style/css/main.css
Labels: enhancement, needs review

#936 907 handle role permission
  CHANGELOG.md
  src/app/account/auth/auth_service.js
  src/app/account/index.js
  src/app/account/user/user_site_role.js
  src/app/basement/index.js
  src/app/basement/restricted_page/restricted_page.html
  src/app/basement/restricted_page/restricted_page.js
  src/app/main/main_controller.js
  src/app/navigation/navigation_controller.js
  src/app/navigation/navigation_view.html
  src/app/site/site_controller.js
  src/app/site/site_view.html
  src/app/team/team_controller.js
  src/app/team/team_view.html
  src/public/languages/en.json
  src/style/css/main.css
Labels: needs review

#939 Release 2018.7.17
  CHANGELOG.md
  src/app/account/auth/auth_service.js
  src/app/account/index.js
  src/app/account/user/user_site_role.js
  src/app/basement/index.js
  src/app/basement/restricted_page/restricted_page.html
  src/app/basement/restricted_page/restricted_page.js
  src/app/entry/entry_edit/editor.css
  src/app/entry/entry_edit/entry_edit_controller.js
  src/app/main/main_controller.js
  src/app/navigation/navigation_controller.js
  src/app/navigation/navigation_view.html
  src/app/site/site_controller.js
  src/app/site/site_view.html
  src/app/team/team_controller.js
  src/app/team/team_view.html
  src/public/languages/en.json
  src/style/css/main.css
Labels: needs review, release

#947 Remove Tour system temporary
  src/app/header/header_controller.js
Labels: needs review

#952 Fix editor where it's content will be unformatted
  CHANGELOG.md
  src/app/entry/entry_edit/editor.js
  src/app/entry/entry_edit/entry_edit_controller.js
  src/app/entry/entry_edit/entry_edit_view.html
Labels: bug, needs review

#950 Add a method to preview post/page at editor
  CHANGELOG.md
  src/app/entry/entry_edit/editor.css
  src/app/entry/entry_edit/entry_edit_controller.js
  src/app/entry/entry_edit/entry_edit_view.html
  src/app/entry/index.js
  src/app/entry/preview_modal/preview_modal_controller.js
  src/app/entry/preview_modal/preview_modal_view.html
  src/app/modals/modals_service.js
Labels: enhancement, needs review
