Repository SavandBros/gonevis-dash, pull requests merged in 2018-08, with the labels that each got.

#956 Release 2018.8.1
  CHANGELOG.md
  src/app/dolphin/dolphin_controller.js
  src/app/entry/entry_edit/editor.css
  src/app/entry/entry_edit/editor.js
  src/app/entry/entry_edit/entry_edit_controller.js
  src/app/entry/entry_edit/entry_edit_view.html
  src/app/entry/index.js
  src/app/entry/preview_modal/preview_modal_controller.js
  src/app/entry/preview_modal/preview_modal_view.html
  src/app/header/header_controller.js
  src/app/modals/modals_service.js
Labels: needs review, release

#957 No auto save when typing post title
  CHANGELOG.md
  src/app/entry/entry_edit/entry_edit_controller.js
  src/app/entry/entry_edit/entry_edit_view.html
Labels: enhancement, needs review

#961 Relase 2018.8.3: No auto save when post title is focused
  CHANGELOG.md
  src/app/entry/entry_edit/entry_edit_controller.js
  src/app/entry/entry_edit/entry_edit_view.html
Labels: needs review, release

#964 Fix post preview
  CHANGELOG.md
  src/app/entry/entry_edit/entry_edit_controller.js
  src/app/entry/entry_service.js
  src/app/entry/preview_modal/preview_modal_controller.js
  src/app/entry/preview_modal/preview_modal_view.html
Labels: needs review, release

#971 Remove theme config section when no configs
  CHANGELOG.md
  src/app/site/site_view.html
Labels: bug, needs review

#967 Fix long file labels
  CHANGELOG.md
  src/style/css/main.css
Labels: bug, needs review
