Repository SavandBros/gonevis-dash, pull requests merged in 2018-05, with the labels that each got.

#833 Update packages
  bower.json
Labels: enhancement, needs review

#834 Make domain list a table and add domain DNS
  app/site/site_view.html
Labels: bug, needs review

#835 Add custom domain DNS target
  app/site/site_view.html
  bower.json
Labels: bug, enhancement, needs review, release

#838 Hide domains table when no domains
  app/site/site_view.html
Labels: bug, needs review

#839 Add option to remove branding
  app/site/site_view.html
Labels: enhancement, needs review

#840 Add remove branding option
  README.md
  app/site/site_view.html
Labels: needs review, release

#844 Add Contributor Covenant Code of Conduct
  CODE_OF_CONDUCT.md
Labels: needs review

#842 Footer text
  app/site/site_view.html
  bower.json
  package.json
Labels: needs review

#847 Fix build
  CODE_OF_CONDUCT.md
  PULL_REQUEST_TEMPLATE.md
  app/site/site_view.html
  bower.json
  package.json
Labels: needs review

#843 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: needs review

#848 Remove gemnasium badge
  README.md
Labels: documentation, needs review

#855 Write publish
  app/app_run.js
  app/assets/css/main.css
  app/entry/entry_edit/entry_edit_controller.js
  app/entry/entry_edit/entry_edit_view.html
  app/entry/entry_new/entry_new_controller.js
  app/entry/entry_new/entry_new_view.html
  app/entry/entry_view.html
  app/entry/includes/entry_form.html
Labels: needs review

#856 Editor update (including design and bug fixes)
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  CODE_OF_CONDUCT.md
  PULL_REQUEST_TEMPLATE.md
  README.md
  app/app_run.js
  app/assets/css/main.css
  app/entry/entry_edit/entry_edit_controller.js
  app/entry/entry_edit/entry_edit_view.html
  app/entry/entry_new/entry_new_controller.js
  app/entry/entry_new/entry_new_view.html
  app/entry/entry_view.html
  app/entry/includes/entry_form.html
  app/site/site_view.html
  bower.json
  gruntfile.js
  package.json
Labels: needs review, release

#860 Update npm packages
  gruntfile.js
  package.json
Labels: needs review

#861 Improve code and performance
  gruntfile.js
  package.json
Labels: needs review, release
