Repository SavandBros/gonevis-dash, pull requests merged in 2018-12, with the labels that each got.

#1030 Update payment method at SiteController
  CHANGELOG.md
  src/app/site/site_controller.js
Labels: enhancement, needs review

#1023 Update google analytics
  CHANGELOG.md
  src/app/api/api_service.js
  src/app/site/site_controller.js
  src/app/site/site_view.html
Labels: enhancement, needs review

#1026 Ability to enable/disable views counter on posts
  CHANGELOG.md
  src/app/site/site_controller.js
  src/app/site/site_view.html
  src/public/languages/en.json
Labels: enhancement, needs review

#1022 Fix videos on paste
  CHANGELOG.md
  src/app/entry/entry_edit/editor.js
Labels: needs review

#1031 Update reader ui
  CHANGELOG.md
  src/app/api/api_service.js
  src/app/reader/index.js
  src/app/reader/reader.css
  src/app/reader/reader_controller.js
  src/app/reader/reader_detail/reader_detail_controller.js
  src/app/reader/reader_detail/reader_detail_view.html
  src/app/reader/reader_service.js
  src/app/reader/reader_view.html
  src/public/languages/en.json
Labels: needs review

#1042 Update plans contents
  CHANGELOG.md
  src/app/site/site_view.html
Labels: enhancement, needs review

#1043 Release 18.12.12
  CHANGELOG.md
  src/app/site/site_view.html
Labels: needs review, release

#1047 Reader back button
  CHANGELOG.md
  src/app/reader/index.js
  src/app/reader/reader_controller.js
  src/app/reader/reader_save_service.js
  src/app/reader/reader_view.html
Labels: enhancement, needs review

#1046 Fix storage metrics on main page
  CHANGELOG.md
  src/app/basement/filters/bytes_filter.js
Labels: needs review

#1048 Add commenting to Reader detail
  CHANGELOG.md
  src/app/reader/reader.css
  src/app/reader/reader_detail/reader_detail_controller.js
  src/app/reader/reader_detail/reader_detail_view.html
  src/public/languages/en.json
Labels: enhancement, needs review

#1052 Release 18.12.13
  CHANGELOG.md
  src/app/basement/filters/bytes_filter.js
  src/app/reader/index.js
  src/app/reader/reader.css
  src/app/reader/reader_controller.js
  src/app/reader/reader_detail/reader_detail_controller.js
  src/app/reader/reader_detail/reader_detail_view.html
  src/app/reader/reader_save_service.js
  src/app/reader/reader_view.html
  src/public/languages/en.json
Labels: needs review, release

#1053 1050 reader comment load more
  CHANGELOG.md
  src/app/basement/pagination/pagination_loadmore.html
  src/app/basement/pagination/pagination_service.js
  src/app/reader/reader_detail/reader_detail_controller.js
  src/app/reader/reader_detail/reader_detail_view.html
Labels: enhancement, needs review

#1054 Update angular and other packages
  package-lock.json
  package.json
Labels: needs review

#1056 Add a method to embed Github Gists.
  CHANGELOG.md
  src/app/basement/embed_listener/embed_listener_service.js
  src/app/basement/index.js
  src/app/entry/entry_edit/editor.js
  src/app/entry/entry_edit/entry_edit_controller.js
  src/app/reader/reader_detail/reader_detail_controller.js
Labels: enhancement, needs review

#1058 Release 2018.12.18
  CHANGELOG.md
  package-lock.json
  package.json
  src/app/basement/embed_listener/embed_listener_service.js
  src/app/basement/index.js
  src/app/basement/pagination/pagination_loadmore.html
  src/app/basement/pagination/pagination_service.js
  src/app/entry/entry_edit/editor.js
  src/app/entry/entry_edit/entry_edit_controller.js
  src/app/reader/reader_detail/reader_detail_controller.js
  src/app/reader/reader_detail/reader_detail_view.html
Labels: enhancement, needs review, release

#1059 Embed both Instagram posts and Twitter tweets into editor.
  CHANGELOG.md
  src/app/entry/entry_edit/editor.js
  src/app/entry/entry_edit/entry_edit_controller.js
Labels: enhancement, needs review

#1060 Release 2018.12.20
  CHANGELOG.md
  src/app/entry/entry_edit/editor.js
  src/app/entry/entry_edit/entry_edit_controller.js
Labels: needs review

#1062 Fix navbar color and design
  CHANGELOG.md
  src/style/css/main.css
Labels: needs review

#1064 Divide post/page list by their statuses
  CHANGELOG.md
  src/app/app_routes.js
  src/app/basement/undo_service/undo_service.js
  src/app/entry/entry.css
  src/app/entry/entry_controller.js
  src/app/entry/entry_edit/entry_edit_controller.js
  src/app/entry/entry_view.html
  src/app/header/header_controller.js
  src/app/main/main_view.html
  src/public/languages/en.json
Labels: enhancement, needs review

#1065 Release 2018.12.22
  CHANGELOG.md
  src/app/app_routes.js
  src/app/basement/undo_service/undo_service.js
  src/app/entry/entry.css
  src/app/entry/entry_controller.js
  src/app/entry/entry_edit/entry_edit_controller.js
  src/app/entry/entry_view.html
  src/app/header/header_controller.js
  src/app/main/main_view.html
  src/public/languages/en.json
  src/style/css/main.css
Labels: needs review

#1066 Add Pastebin embed
  CHANGELOG.md
  src/app/entry/entry_edit/entry_edit_controller.js
Labels: enhancement, needs review

#1067 Add SoundCloud embed
  CHANGELOG.md
  src/app/entry/entry_edit/editor.js
  src/app/entry/entry_edit/entry_edit_controller.js
Labels: enhancement, needs review

#1068 Release 2018.12.24
  CHANGELOG.md
  src/app/entry/entry_edit/editor.js
  src/app/entry/entry_edit/entry_edit_controller.js
Labels: enhancement, needs review

#1070 Fix YouTube embed getting smaller on post/page update.
  CHANGELOG.md
  src/app/entry/entry_edit/editor.js
Labels: needs review

#1071 Release 2018.12.24
  CHANGELOG.md
  src/app/entry/entry_edit/editor.js
Labels: needs review

#1073 Fix editor being wrapped in code-block.
  CHANGELOG.md
  src/app/entry/entry_edit/entry_edit_controller.js
Labels: needs review

#1074 Release 2018.12.24
  CHANGELOG.md
  src/app/entry/entry_edit/entry_edit_controller.js
Labels: needs review

#1076 Fix editor code paste
  CHANGELOG.md
  src/app/entry/entry_edit/editor.js
Labels: needs review

#1077 Release 2018.12.25
  CHANGELOG.md
  src/app/entry/entry_edit/editor.js
Labels: needs review
