Repository SavandBros/gonevis-dash, pull requests merged in 2018-06, with the labels that each got.

#878 Translating now
  .tx/config
  package-lock.json
  package.json
  src/app/app.js
  src/app/app_config.js
  src/app/header/header_controller.js
  src/app/header/header_view.html
  src/app/vendor.js
  src/public/index.html
  src/public/languages/en.json
  src/public/languages/fa.json
Labels: enhancement, i18n, needs review

#883 Create tags at entry even if they don't exist
  src/app/entry/entry_edit/entry_edit_controller.js
  src/app/entry/entry_edit/entry_edit_view.html
  src/app/entry/includes/entry_form.html
Labels: enhancement, needs review, text editor

#888 Remove chart js
  package-lock.json
  package.json
  src/app/app_routes.js
  src/app/main/main_controller.js
  src/app/main/main_view.html
  src/style/css/main.css
Labels: enhancement, needs review

#889 Shorter sidebar
  src/style/css/ice.css
Labels: enhancement, needs review

#896 Use PUT method for changing password
  src/app/account/change_pass/change_pass_controller.js
Labels: needs review

#897 Syncing translation files from source
  package.json
  scripts/sync_trans.js
Labels: enhancement, needs review

#900 Incomplete profile alert
  package-lock.json
  package.json
  src/app/account/account_service.js
  src/app/account/user/user_view.html
  src/app/main/main_controller.js
  src/app/main/main_view.html
  src/public/languages/en.json
  src/public/languages/fa.json
  src/style/css/ice.css
  test/spec/account/account_service.js
Labels: i18n, needs review

#894 Add translation to all parts
  CHANGELOG.md
  src/app/account/change_pass/change_pass_controller.js
  src/app/account/change_pass/change_pass_view.html
  src/app/account/email_confirmation/email_confirmation_controller.js
  src/app/account/email_confirmation/email_confirmation_modal.html
  src/app/account/email_confirmation/email_confirmation_view.html
  src/app/account/forgot_modal/forgot_modal_controller.js
  src/app/account/forgot_modal/forgot_modal_view.html
  src/app/account/reset_pass/reset_pass_view.html
  src/app/account/signin/signin_controller.js
  src/app/account/signin/signin_view.html
  src/app/account/signup/signup_controller.js
  src/app/account/signup/signup_view.html
  src/app/account/user/user_controller.js
  src/app/account/user/user_view.html
  src/app/basement/codekit/codekit_service.js
  src/app/basement/pagination/pagination_loadmore.html
  src/app/basement/search/search_form.html
  src/app/basement/search/search_noresult.html
  src/app/comment/comment_modal/comment_modal_view.html
  src/app/comment/comment_service.js
  src/app/comment/comment_view.html
  src/app/dolphin/dolphin_controller.js
  src/app/dolphin/dolphin_modal/dolphin_modal_controller.js
  src/app/dolphin/dolphin_modal/dolphin_modal_view.html
  src/app/dolphin/dolphin_selection.html
  src/app/dolphin/dolphin_service.js
  src/app/dolphin/dolphin_view.html
  src/app/entry/entry_controller.js
  src/app/entry/entry_edit/entry_edit_controller.js
  src/app/entry/entry_edit/entry_edit_view.html
  src/app/entry/entry_service.js
  src/app/entry/entry_view.html
  src/app/header/header_controller.js
  src/app/main/main_view.html
  src/app/navigation/navigation_controller.js
  src/app/navigation/navigation_view.html
  src/app/site/site_controller.js
  src/app/site/site_new/site_new_controller.js
  src/app/site/site_new/site_new_view.html
  src/app/site/site_templates_modal/site_templates_modal_view.html
  src/app/site/site_view.html
  src/app/start/start_controller.js
  src/app/start/start_view.html
  src/app/tag/tag_modal/tag_modal_view.html
  src/app/tag/tag_service.js
  src/app/tag/tag_view.html
  src/app/team/invite_modal/invite_modal_controller.js
  src/app/team/invite_modal/invite_modal_view.html
  src/app/team/team_modal/team_modal_controller.js
  src/app/team/team_modal/team_modal_view.html
  src/app/team/team_view.html
  src/public/languages/en.json
  test/spec/account/change_pass.js
Labels: enhancement, i18n, needs review

#898 Fix tab's title on state change (fix ui router)
  CHANGELOG.md
  src/app/app_run.js
Labels: needs review

#903 Add updated by username
  CHANGELOG.md
  src/app/entry/entry_view.html
  src/public/languages/en.json
Labels: enhancement, needs review

#902 Show site followers
  CHANGELOG.md
  envs/dev.json
  envs/production.json
  envs/staging.json
  src/app/api/api_service.js
  src/app/basement/pagination/pagination_loadmore.html
  src/app/main/main_controller.js
  src/app/main/main_view.html
  src/app/modals/modals_service.js
  src/app/site/index.js
  src/app/site/site_followers/site_followers_controller.js
  src/app/site/site_followers/site_followers_view.html
  src/public/languages/en.json
  src/style/css/shorties.css
Labels: enhancement, needs review

#909 Skip tour
  CHANGELOG.md
  package-lock.json
  src/app/basement/tour/tour_service.js
  src/app/header/header_view.html
  src/public/languages/en.json
  src/public/languages/fa.json
  src/style/css/main.css
Labels: needs review

#908 Drag drop files to upload
  CHANGELOG.md
  src/app/app_run.js
  src/app/dolphin/dolphin_controller.js
  src/app/dolphin/dolphin_selection.html
  src/app/dolphin/dolphin_view.html
  src/public/index.html
  src/public/languages/en.json
  src/style/css/main.css
  src/style/css/shorties.css
Labels: enhancement, needs review

#912 Upgrading to CircleCI version 2
  .circleci/config.yml
  .jshintrc
  CHANGELOG.md
  README.md
  circle.yml
  package-lock.json
  package.json
  src/app/account/account_service.js
  src/app/account/auth/auth_service.js
  src/app/account/email_confirmation/email_confirmation_controller.js
  src/app/app_config.js
  src/app/app_routes.js
  src/app/app_run.js
  src/app/basement/filters/timesince_filter.js
  src/app/basement/filters/timeuntil_filter.js
  src/app/basement/medium_editor/medium_editor.js
  src/app/basement/pagination/pagination_service.js
  src/app/entry/entry_edit/entry_edit_controller.js
  src/app/tag/tag_controller.js
  src/app/tag/tag_modal/tag_modal_controller.js
  src/app/team/team_modal/team_modal_controller.js
Labels: needs review

#913 Minimal followers layout
  CHANGELOG.md
  src/app/basement/pagination/pagination_loadmore.html
  src/app/basement/pagination/pagination_service.js
  src/app/site/site_followers/site_followers_view.html
  src/style/css/main.css
Labels: needs review
