Repository SavandBros/gonevis-dash, pull requests merged in 2018-10, with the labels that each got.

#984 Improve sidebar
  CHANGELOG.md
  src/app/header/header_controller.js
  src/app/header/header_view.html
  src/style/css/ice.css
  src/style/css/main.css
Labels: enhancement, needs review

#966 Improve editor
  src/app/app_routes.js
  src/app/app_run.js
  src/app/basement/directives/auto_resize_directive.js
  src/app/basement/index.js
  src/app/basement/undo_service/undo_service.js
  src/app/entry/entry_controller.js
  src/app/entry/entry_edit/editor.css
  src/app/entry/entry_edit/editor.js
  src/app/entry/entry_edit/entry_edit_controller.js
  src/app/entry/entry_edit/entry_edit_view.html
  src/app/entry/entry_service.js
  src/app/entry/entry_view.html
  src/app/entry/preview_modal/preview_modal_view.html
  src/app/header/header_controller.js
  src/app/reader/reader_detail/reader_detail_controller.js
  src/public/index.html
  src/public/languages/en.json
  src/style/css/ice.css
  src/style/css/main.css
Labels: enhancement, needs review

#975 Feedback form
  CHANGELOG.md
  src/app/api/api_service.js
  src/app/feedback/feedback_controller.js
  src/app/feedback/feedback_view.html
  src/app/feedback/index.js
  src/app/header/header_controller.js
  src/app/header/header_view.html
  src/app/index.js
  src/app/modals/modals_service.js
  src/public/languages/en.json
  test/spec/feedback/feedback_controller.js
Labels: blocked, needs review

#960 Added #863: Explore and Feed
  CHANGELOG.md
  src/app/account/auth/auth_interceptor_service.js
  src/app/account/user/user_controller.js
  src/app/api/api_service.js
  src/app/app_routes.js
  src/app/app_run.js
  src/app/basement/directives/auto_resize_directive.js
  src/app/basement/index.js
  src/app/basement/undo_service/undo_service.js
  src/app/entry/entry_controller.js
  src/app/entry/entry_edit/editor.css
  src/app/entry/entry_edit/editor.js
  src/app/entry/entry_edit/entry_edit_controller.js
  src/app/entry/entry_edit/entry_edit_view.html
  src/app/entry/entry_service.js
  src/app/entry/entry_view.html
  src/app/entry/preview_modal/preview_modal_controller.js
  src/app/entry/preview_modal/preview_modal_view.html
  src/app/feedback/feedback_controller.js
  src/app/feedback/feedback_view.html
  src/app/feedback/index.js
  src/app/header/header_controller.js
  src/app/header/header_view.html
  src/app/index.js
  src/app/main/main_view.html
  src/app/modals/modals_service.js
  src/app/reader/index.js
  src/app/reader/reader.css
  src/app/reader/reader_controller.js
  src/app/reader/reader_detail/reader_detail_controller.js
  src/app/reader/reader_detail/reader_detail_view.html
  src/app/reader/reader_view.html
  src/app/site/site_controller.js
  src/app/site/site_new/site_new_controller.js
  src/app/site/site_new/site_new_view.html
  src/app/site/site_view.html
  src/app/start/start_view.html
  src/app/tag/tag_modal/tag_modal_view.html
  src/app/tag/tag_view.html
  src/public/index.html
  src/public/languages/en.json
  src/style/css/ice.css
  src/style/css/main.css
  src/style/css/shorties.css
  test/spec/feedback/feedback_controller.js
Labels: enhancement, needs review

#990 Reader
  CHANGELOG.md
  src/app/account/auth/auth_interceptor_service.js
  src/app/account/user/user_controller.js
  src/app/api/api_service.js
  src/app/app_routes.js
  src/app/app_run.js
  src/app/basement/directives/auto_resize_directive.js
  src/app/basement/index.js
  src/app/basement/undo_service/undo_service.js
  src/app/entry/entry_controller.js
  src/app/entry/entry_edit/editor.css
  src/app/entry/entry_edit/editor.js
  src/app/entry/entry_edit/entry_edit_controller.js
  src/app/entry/entry_edit/entry_edit_view.html
  src/app/entry/entry_service.js
  src/app/entry/entry_view.html
  src/app/entry/preview_modal/preview_modal_view.html
  src/app/feedback/feedback_controller.js
  src/app/feedback/feedback_view.html
  src/app/feedback/index.js
  src/app/header/header_controller.js
  src/app/header/header_view.html
  src/app/index.js
  src/app/modals/modals_service.js
  src/app/reader/index.js
  src/app/reader/reader.css
  src/app/reader/reader_controller.js
  src/app/reader/reader_detail/reader_detail_controller.js
  src/app/reader/reader_detail/reader_detail_view.html
  src/app/reader/reader_view.html
  src/app/site/site_controller.js
  src/public/index.html
  src/public/languages/en.json
  src/style/css/ice.css
  src/style/css/main.css
  src/style/css/shorties.css
  test/spec/feedback/feedback_controller.js
Labels: needs review
