Repository SavandBros/gonevis-dash, pull requests merged in 2018-04, with the labels that each got.

#824 Don't show domain error on prompt cancel
  app/site/site_controller.js
Labels: ready

#825 Fix custom domain alert
  app/site/site_controller.js
Labels: in progress

#829 Create page entries
  app/app_routes.js
  app/entry/entry_new/entry_new_controller.js
  app/entry/entry_view.html
  app/entry/includes/entry_form.html
Labels: bug, needs review

#830 Create posts as pages
  app/app_routes.js
  app/entry/entry_new/entry_new_controller.js
  app/entry/entry_view.html
  app/entry/includes/entry_form.html
Labels: in progress, release
