Repository SavandBros/gonevis-dash, pull requests merged in 2019-04, with the labels that each got.

#1154 Fix dark mode on reader and post/page edition.
  CHANGELOG.md
  src/app/entry/entry_edit/editor.css
Labels: needs review

#1156 Fix top margin on main wrapper.
  CHANGELOG.md
  src/app/reader/reader.css
  src/style/css/main.css
Labels: needs review

#1152 Bring back excerpt at entry form
  CHANGELOG.md
  src/app/entry/entry_edit/entry_edit_view.html
  src/public/languages/en.json
Labels: needs review

#1157 Release 2019.4.4
  .circleci/config.yml
  CHANGELOG.md
  src/app/entry/entry_edit/editor.css
  src/app/entry/entry_edit/entry_edit_view.html
  src/app/reader/reader.css
  src/public/languages/en.json
  src/public/languages/es.json
  src/public/languages/fa.json
  src/public/languages/ru.json
  src/style/css/main.css
Labels: needs review, release

#1160 WIP: Ability to change theme's primary color
  CHANGELOG.md
  src/app/site/site_controller.js
  src/app/site/site_view.html
  src/public/languages/en.json
Labels: enhancement

#1161 Release 2019.4.7
  CHANGELOG.md
  src/app/site/site_controller.js
  src/app/site/site_view.html
  src/public/languages/en.json
  src/public/languages/fa.json
Labels: release

#1164 Resolve "Google AdService Conversion"
  CHANGELOG.md
  src/app/account/signup/signup_controller.js
  src/public/index.html
Labels: enhancement

#1167 Change profile setting input UI
  CHANGELOG.md
  src/app/account/user/user_controller.js
  src/app/account/user/user_view.html
  src/public/languages/en.json
  src/style/css/main.css
Labels: enhancement

#1166 2019.4.7-2
  CHANGELOG.md
  src/app/account/signup/signup_controller.js
  src/app/account/user/user_controller.js
  src/app/account/user/user_view.html
  src/public/index.html
  src/public/languages/en.json
  src/style/css/main.css
Labels: release

#1169 Release 2019.4.7-3
  CHANGELOG.md
  src/app/account/signin/signin_view.html
  src/app/account/signup/signup_view.html
  src/style/css/shorties.css
Labels: release

#1174 Resolved "Add Discord invite"
  CHANGELOG.md
  envs/dev.json
  envs/production.json
  envs/staging.json
  src/app/help/help.css
  src/app/help/help_controller.js
  src/app/help/help_view.html
  src/app/main/main.css
  src/app/main/main_controller.js
  src/app/main/main_view.html
  src/public/img/discord.svg
  src/public/languages/en.json
  src/public/languages/fa.json
Labels: enhancement

#1175 Release 2019.4.10
  CHANGELOG.md
  envs/dev.json
  envs/production.json
  envs/staging.json
  src/app/help/help.css
  src/app/help/help_controller.js
  src/app/help/help_view.html
  src/app/main/main.css
  src/app/main/main_controller.js
  src/app/main/main_view.html
  src/public/img/discord.svg
  src/public/languages/en.json
  src/public/languages/fa.json
Labels: release

#1177 Release 2019.4.14
  CHANGELOG.md
  src/app/basement/search/search_form.html
  src/app/basement/view/top_bar.html
  src/app/entry/entry.css
  src/app/entry/entry_controller.js
  src/app/entry/entry_view.html
  src/app/site/site_controller.js
Labels: release

#1183 Resolve "Add comment support to reader"
  CHANGELOG.md
  src/app/api/api_service.js
  src/app/comment/comment_service.js
  src/app/reader/reader.css
  src/app/reader/reader_detail/reader_detail_controller.js
  src/app/reader/reader_detail/reader_detail_view.html
  src/public/languages/en.json
Labels: ready
