Repository SavandBros/gonevis-dash, pull requests merged in 2019-02, with the labels that each got.

#1108 Update packages
  CHANGELOG.md
  package-lock.json
  package.json
Labels: needs review

#1112 Hide new year message
  CHANGELOG.md
  src/app/header/header_view.html
Labels: needs review

#1114 Release 2019.2.3
  CHANGELOG.md
  package-lock.json
  package.json
  src/app/header/header_view.html
Labels: needs review, release

#1115 Resolve "Add details to incomplete-profile alert"
  CHANGELOG.md
  src/app/account/account_service.js
  src/app/main/main_view.html
  src/public/languages/en.json
Labels: needs review

#1116 Release 2019.2.4
  CHANGELOG.md
  src/app/account/account_service.js
  src/app/main/main_view.html
  src/public/languages/en.json
Labels: needs review, release

#1120 Add Vimeo video URL support
  CHANGELOG.md
  src/app/entry/entry_edit/editor.js
  src/app/entry/entry_edit/entry_edit_controller.js
Labels: enhancement, needs review

#1118 Fix blog domain list doesn't show up
  CHANGELOG.md
  src/app/site/site_view.html
Labels: needs review

#1121 Release 2019.3.15
  CHANGELOG.md
  src/app/entry/entry_edit/editor.js
  src/app/entry/entry_edit/entry_edit_controller.js
  src/app/site/site_view.html
Labels: needs review, release

#1123 Only embed url when ever user pastes an URL
  CHANGELOG.md
  src/app/entry/entry_edit/entry_edit_controller.js
Labels: needs review

#1127 Change blue to project's primary color at 'header' option at editor buttons
  CHANGELOG.md
  src/app/entry/entry_edit/editor.css
Labels: needs review

#1125 Fix ux for save buttons
  CHANGELOG.md
  src/app/site/site_view.html
Labels: needs review

#1131 Remove entry from draft when published and vise versa
  CHANGELOG.md
  src/app/entry/entry_controller.js
  src/app/entry/entry_service.js
Labels: needs review

#1134 Resolves "Remove "Remove branding" and "Google Analytics" sections and from other setting tabs."
  CHANGELOG.md
  src/app/site/site_view.html
Labels: needs review

#1135 Release 2018.2.23
  CHANGELOG.md
  src/app/entry/entry_controller.js
  src/app/entry/entry_edit/editor.css
  src/app/entry/entry_edit/entry_edit_controller.js
  src/app/entry/entry_service.js
  src/app/site/site_view.html
Labels: needs review, release
